name: build
on:
  pull_request:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - main
      - "releases/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gobabygo
        uses: ./
